# pnpm workspace configuration
# Defines all packages in the monorepo

packages:
  - "packages/*"

# Exclude build outputs and dependencies
exclude:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.next/**"
  - "**/.astro/**"
